# Travis CI configuraion for the W3 Total Cache WordPress plugin by BoldGrid.
# @link https://make.wordpress.org/cli/handbook/misc/plugin-unit-tests/#running-tests-on-travis-ci

language: php

services:
  - mysql

notifications:
  slack:
    secure: Me2FCeSQNVpIx7lvf5o9gTP60+WQiaxwDIeTsE9NB6+fHRDwrt5Jju1sTXbEgbB7CDQWKuAL6CouL4ZOoUUtHe00u6D0ifwDhj1M3IMeD3NjnWr2dbvZltHkMTCLbtdfD6F5VLhYWFTSNLS4EQAOuITCi1Ph4H+WcYttaw4ldbauSmPnKRvaLGh6tHG+/zLzwdhlwUVeT3hGtZdZXB2mibxtvdx+fMJIBcd0q+smI7VIMQXKNsZ/BZ8QW/qRO2neWI3CBYigeNwXuvlxYv/UBBgneBaPGYNo3DcwHARPTSwKByyLzbG+fN4ymx7iRioQ0x74Dex16u7BNhyeOdj8E3MxR3wDTlUkwXXDJI2YpBp/jmB3lPpEu+LPUxlBV5d8HuiMSf1g4vc2VBBUypWBjq2wWCyQzuRcKDwiyc60bFKtSCOHIzRwO+hDHLW7INzDedA2W0JYerLEgmlQj7yVB8Ly4dl38Gals/X4+y4gkpOSKyCsvAOePYcPFs+BIUMRVR3kueF3fu/sWGQEDJD2oTljLm45ue/x7ytyQOHVw94Ao0A0sf1G1nMwqmIFT90z137yGrlwoh8vXHeUWxFfPV6TB75+E8QLFjoo0Gs3nzfi//kd7UMlnRKkuF1+/5Hvo3VS3GTo0nO6Xo3dCHT2f4HZdR5PVZqhTGAPxdgORa8=

matrix:
  include:
    -
      php: 7.2
      dist: bionic
      before_script:
        - composer self-update
        - composer update
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost
        #- yarn run php-codesniffer
    -
      php: 8.1
      dist: jammy
      before_script:
        - composer update
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost
        #- yarn run php-codesniffer

install:
  - nvm install 20
  - nvm use 20
  - yarn install

script:
  # PHPUnit: Run unit tests.
  - vendor/phpunit/phpunit/phpunit --debug --verbose --coverage-clover=coverage.xml
  # JavaScript lint.
  #- yarn run js-lint
  # Remove dev dependencies.
  - composer install --no-dev -o
  # PHP lint.
  - find . -name composer -prune -o -name node_modules -prune -o -name '*.php' -exec php -lf {} \; > /dev/null

after_success:
  # Codecov: Create a code coverage report for PHP 7.2.
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -f coverage.xml; fi

deploy:
  - provider: script
    script: chmod +x ./bin/release.sh && ./bin/release.sh
    skip_cleanup: true
    on:
      tags: true
      php: 7.2
  - provider: releases
    api_key: "${GITHUB_TOKEN}"
    file: "w3-total-cache.zip"
    skip_cleanup: true
    on:
      tags: true
      php: 7.2
